// frontend/src/components/landing/TrustedBySection.vue
<template>
  <section class="trusted-section" aria-label="服务能力">
    <div class="trusted-inner">
      <p class="trusted-label">Partnered with top-tier companies globally</p>
      <LandingMarquee wrap-class="trusted-marquee" :items="trustedCompanies">
        <template #default="{ item }">
          <span :class="item.className">{{ item.name }}</span>
        </template>
      </LandingMarquee>
    </div>
  </section>
</template>

<script setup lang="ts">
import { trustedCompanies } from '@/data/landing'
import LandingMarquee from './LandingMarquee.vue'
</script>

// react-frontend/src/components/TrustedBySection.tsx
import { trustedCompanies } from '../data/alwayzz'
import { Marquee } from './Marquee'

export function TrustedBySection() {
  return (
    <section className="trusted-section" aria-label="服务能力">
      <div className="trusted-inner">
        <p className="trusted-label">Partnered with top-tier companies globally</p>
        <Marquee
          className="trusted-marquee"
          items={trustedCompanies}
          renderItem={(company) => <span className={company.className}>{company.name}</span>}
        />
      </div>
    </section>
  )
}
